### ISSUE TITLE
FPS drops

### ISSUE THREAD

**Issue by agentwolf88** [Meldexun/BetterDiving#1]
There are extremely fps drop when i equip the items (mask, tank, leggins and fins).

**Comment by agentwolf88** [comment]
When i equip the armor in the inventory the fps are very low and stay low. When i exit the inventory the game runs normal with high fps. When i go back to the inventory the fps drop again.

**Comment by Meldexun** [comment]
I see. It's probably because of the custom model and the model is just loaded in the inventory or 3rd person view. I will take a look at this. But there won't be an update today.

**Comment by agentwolf88** [comment]
ok, thx. keep up the good work.

**Comment by Meldexun** [comment]
I uploaded v1.0.3 which hopefully fixes the performance issue. I would be glad if you could tell me your results.

**Comment by agentwolf88** [comment]
Thank you, i will test it later.

**Comment by agentwolf88** [comment]
Its fixed, thx! But now is crashing my server at startup. https://github.com/Meldexun/BetterDiving/issues/2
