### ISSUE TITLE
Artifact Snorkel doesn't work with Better Diving installed

### ISSUE THREAD

**Issue by relsqui** [Meldexun/BetterDiving#106]
**Describe the bug**
The snorkel from [Artifacts](https://www.curseforge.com/minecraft/mc-mods/artifacts) grants water breathing. When I wear it with Better Diving installed, my O2 tank depletes until empty, then I drown.

I don't know enough about mod internals to tell which mod is actually causing this (or can more easily fix it) -- happy to take it to the Artifacts tracker instead if need be.

**To Reproduce**
1. Install Artifacts and Better Diving
2. Acquire and equip snorkel
3. Stay under water until oxygen runs out
4. Drown

**Versions**
Better Diving: 1.2.3
Artifacts: 1.16.5-2.8.4
Forge: 36.1.13
Minecraft: 1.16.5

**Other**
Singleplayer/Multiplayer: SSP
Other mods (that are necessary to produce the bug): Artifacts
Other mods (that are also installed): [This pack](https://www.curseforge.com/minecraft/modpacks/swords-to-plowshares) (just uploaded so it might take a bit to be visible)

**Comment by Meldexun** [comment]
Works fine for me

**Comment by relsqui** [comment]
Oh, interesting -- I'll have to experiment more and figure out what's going wrong. Any suggestions for what to look at? (The only other relevant thing I can think of is that I was wearing a helmet with Respiration III at the time.)

**Comment by Meldexun** [comment]
You are getting the water breathing effect from the snorkel right? Then you can try unequipping it and drink a water breathing potion instead.

**Comment by relsqui** [comment]
I mean, apparently I'm not because I'm drowning, but if you can't repro it's probably not because of this mod. I'll try some different mod combinations and take it over to the Artifacts tracker. Thanks for the quick response!

**Comment by Meldexun** [comment]
I mean when I equip the snorkel I see the water breathing effect when my inventory is open. If that is not the case for you then it is most probably not caused by better diving.

**Comment by relsqui** [comment]
Aha, the conflict turned out to be with Atlantis. Sorry to bug you prematurely, thanks for the help!
