### ISSUE TITLE
Limestone Outcrop question

### ISSUE THREAD

**Issue by sadboi123** [Meldexun/BetterDiving#107]
**Question**
I dont know if I'm doing something wrong but I cannot find a limestone outcrop for titanium. I've searched under the sea but to no avail.

**Versions**
Better Diving:1.5.8
Forge:14.23.5.2854
Minecraft:1.12.2

**Other**
Crash report (if one exists):nope
Latest log:idk
Singleplayer/Multiplayer:Multiplayer but its a LAN world
Other mods (that are necessary to produce the bug):see below
Other mods (that are also installed):I'm using the Rouge-Like Adventures and Dungeons modpack

**Comment by Meldexun** [comment]
It's probably disabled in your modpack. You should ask the modpack author where you can find titanium.
