### ISSUE TITLE
mekanism skuba tanks deplete way to quick when this mod is on

### ISSUE THREAD

**Issue by benbenlaw** [Meldexun/BetterDiving#108]
**Describe the bug**
mekanism skuba tanks deplete way to quick when this mod is on

**To Reproduce**
1 equipe mekanism skuba gear
2 enter water skuba gear oxygen depletes instantly

**Versions**
Better Diving: 1.2.3
Forge: 36.1.16
Minecraft: 1.16.5

**Other**
Crash report (if one exists):
Latest log:
Singleplayer/Multiplayer:
Other mods (that are necessary to produce the bug):
Other mods (that are also installed):

**Comment by Meldexun** [comment]
Should be reported to the mekanism issue tracker. I have an api jar available now which should make it easy for them to fix this:
https://www.curseforge.com/minecraft/mc-mods/better-diving/files/3312634

**Comment by Meldexun** [comment]
Should be fixed in BetterDiving-1.16.5-1.3.0-beta
