### ISSUE TITLE
No mouse control available for Seamoth

### ISSUE THREAD

**Issue by VallenFrostweaver** [Meldexun/BetterDiving#109]
**Describe the bug**
Controls of the Seamoth are only on one horizontal plane. Moving the mouse does not change the seamoth direction at all. Directional controls are only accessible via WASD and C for descend.

**Versions**
Better Diving: 1.2.3
Forge: 36.1.2
Minecraft: 1.16.5

**Other**
Crash report (if one exists):
Latest log:
Singleplayer/Multiplayer:
Other mods (that are necessary to produce the bug):
Other mods (that are also installed):

**Comment by Meldexun** [comment]
I updated the issue to match the issue template. Please provide the requested information.
Also does the seamoth have a non-empty energy cell?

**Comment by Meldexun** [comment]
I think I was able to reproduce this:
I placed a seamoth without a power cell in the world and then right clicked it to enter it.
Then I opened the inventory and placed a power cell into the seamoth.
The seamoth is now not correctly synced and I was unable to turn around.

Though I also noticed that after leaving and entering the seamoth again it worked fine.

**Comment by Meldexun** [comment]
Fixed in v1.16.5-1.2.5
