### ISSUE TITLE
Sharp fog border when using colored fog

### ISSUE THREAD

**Issue by juraj-hrivnak** [Meldexun/BetterDiving#111]
**The bug**
There is a very sharp non-fogy edge in the water.
The bug is better described by screenshots...
![2021-05-30_00 33 28](https://user-images.githubusercontent.com/71150936/120086482-b0b7af00-c0df-11eb-9d9c-448eeacad485.png)
![2021-05-30_00 38 56](https://user-images.githubusercontent.com/71150936/120086484-b1e8dc00-c0df-11eb-8ba9-82db976686cd.png)

**To Reproduce**
Anable the `FogColor` in `ClientSettings/Fog`
Dive into the water, and see

**Versions**
Better Diving: `1.12.2-1.5.8`
Forge: `1.12.2 - 14.23.5.2855`
Minecraft: `1.12.2`

**Other**
Other mods (that are necessary to produce the bug): N/A
Other mods (that are also installed): N/A

**Comment by juraj-hrivnak** [comment]
Sow that other mod (TerraFirmaCraft) have coloured water and without this border, so I was wondering if it's not possible to fix it here.

**Comment by Meldexun** [comment]
Not a bug of better diving. It's a problem of minecraft's skybox rendering.
Also 1.12.2 isn't worked on anymore.

**Comment by juraj-hrivnak** [comment]
Oh, I see! Thanks
