### ISSUE TITLE
Oxygen meter visibility outside of water?

### ISSUE THREAD

**Issue by Darkmega18** [Meldexun/BetterDiving#112]
**Question**
Is there still an option to enable the gui to render even when outside of water? If there isn't, will you re-implement it? Since I recall 1.12.2 had different oxygen meter skins and also the ability to render it always or only when it's going down and such but I can't seem to find such a setting in client or server configs for this.

I have origins forge installed and I can't keep an eye on my meter while outside of water to see if it's playing well with this as a Waterborn or incase any other mechanics drain breathe above land or in any other locations for some reason or another in anything else I could be using. 

Since I'm testing stuff and theres probably a better bauble somewhere that does land suffocating or breathing extensions etc for when I do testing to ask for fixes towards them against or with this.

**Versions**
Better Diving: 1.2.5
Forge: 36.1.24
Minecraft: 1.16.5

**Other**
Singleplayer/Multiplayer: both. probably.
Other mods (that are also installed): plenty. :V too numerous to mention just for this question and suggestion.

**Comment by Meldexun** [comment]
The 1.16 has no alternative oxygen gui (and there won't be one in the future). The oxygen gui shows when the player is underwater or his oxygen is less than his oxygen capacity.

**Comment by Darkmega18** [comment]
Can it be made to just show when oxygen is lower than capacity regardless of submerged in water or not?

**Comment by Meldexun** [comment]
That already is the case

**Comment by Darkmega18** [comment]
I don't think it is. I've looked over both the client config and the server config numerous times, searching every config related to oxygen and gui and there doesn't seem to be such a setting unless theres something going on ingame.

**Comment by Darkmega18** [comment]
looks like I'm gonna have to test and check on some stuff and do some bug reports to some places then which do things to do with suffocation outside of liquids and such. :V

**Comment by Meldexun** [comment]
Compatibility with other mods was reworked in v1.16.5-1.3.0-beta and shouldn't be an issue anymore

**Comment by Darkmega18** [comment]
sounds good, hopefully.
