### ISSUE TITLE
Seamoth inventory can't be opened

### ISSUE THREAD

**Issue by benbenlaw** [Meldexun/BetterDiving#114]
**Describe the bug**
seamoth inventory not loading anymore meaning the seamoth cannot move

**To Reproduce**
1. press e to open seamoth inventory nothing happens

**Versions**
Better Diving: 1.3.0-beta
Forge: 36.2.2
Minecraft: 1.16.5

**Comment by Meldexun** [comment]
Next time please fill out the issue template completely and correctly.

**Comment by Meldexun** [comment]
Fixed in v1.16.5-1.3.1

**Comment by benbenlaw** [comment]
what did i do wrong ?

**Comment by Meldexun** [comment]
Yes, the **Other** section is missing (Now it's already fixed and thus it's fine now) and you said that you are using v1.16.5-1.2.5 though the bug only exists in v1.16.5-1.3.0-beta (I edited that part).

**Comment by benbenlaw** [comment]
sorry haha i know how annoying it can be filling in the bug report wrong haha
