### ISSUE TITLE
Construct's Armory Amphibious Compatability

### ISSUE THREAD

**Issue by crimsonDestroyer** [Meldexun/BetterDiving#115]
Currently, using this mod renders the Construct's Armory modifier "Amphibious" (effectively just an air tank you can attach to your helmet that stores oxygen to use underwater) completely useless. It would be nice if this wasn't the case. Maybe a general-purposes thing to allow mods that alter underwater breathing to function with the Better Diving oxygen system.

**Comment by Meldexun** [comment]
Next time please fill out the issue template completely.
Also 1.12 is no longer supported and thus this will be closed now.
