### ISSUE TITLE
how to get titanium? cant find it.

### ISSUE THREAD

**Issue by TURRETCUBE123** [Meldexun/BetterDiving#116]
**Describe the bug**

**To Reproduce**
1. Go to...
2. Use item...
3. Place block...
.
.
.

**Versions**
Better Diving:
Forge:
Minecraft:

**Other**
Crash report (if one exists):
Latest log:
Singleplayer/Multiplayer:
Other mods (that are necessary to produce the bug):
Other mods (that are also installed):

**Comment by pivinx1** [comment]
This is not a bug as far as I know, titanium drops from limestone outcrops, just break them.
