### ISSUE TITLE
Config file ignoring custom diving gear armor values

### ISSUE THREAD

**Issue by Boolyman** [Meldexun/BetterDiving#118]
**Describe the bug**
Changes I made in the config file are not changing the armor value of the diving gear in-game.

**To Reproduce**
1. Edit config file to increase the armor of diving gear.
2. Load Minecraft
3. Be surprised when the diving gear still has the default armor values.

**Versions**
Better Diving:  BetterDiving-1.16.5-1.3.2
Forge: 36.2.8
Minecraft: 1.16.5

**Other**
Config File - https://paste.gg/p/anonymous/e8217870b37547218209012094d9a4d3

**Comment by Meldexun** [comment]
Fixed in v1.16.5-1.3.4
