### ISSUE TITLE
Charged seamoth almost totally unresponsive to mouse  

### ISSUE THREAD

**Issue by quinelet** [Meldexun/BetterDiving#120]
**Describe the bug**
Entering seamoth after ensuring it has a charged power cell, I cannot effectively control the seamoth with the mouse. After some experimentation, I was able to find that moving the mouse quite a lot sometimes causes minor changes to orientation.  Additionally, within the first 15 seconds or so of entering the world, I was able to make a 15 degree course adjustment while minecraft was still pretty laggy.

I have tried both a USB optical mouse and a trackpad on my laptop, tried altering each of the mouse input options in the minecraft settings window, tried disabling my laptop's touchscreen, tried unplugging and replugging the mouse, etc. Nothing appears to allow me to significantly adjust the heading of the seamoth over timescales less than several minutes.

I also ensured there was a charged cell inside the seamoth, and tried entering and exiting it a few times, have tried breaking, replacing the seamoth, taking out and reinserting the (charged) powercell, tried recharging the power cell to 100% and THEN trying it - no luck.

**To Reproduce**
1. Get in seamoth.
2. Move mouse a round. Tiny heading adjustments are occasionally seen.

**Versions**
Better Diving: 1.16.5-1.3.2
Forge:  36.2.9
Minecraft: 1.16.5-forge-36.2.9

As part of FTB OceanBlock 1.7.0 [beta]

**Other**
Crash report (if one exists): N/A

Latest log: 
https://pastebin.com/Mdmnm4Ms

Singleplayer/Multiplayer: singleplayer

Other mods (that are necessary to produce the bug):
Other mods (that are also installed):
Everything in FTB OceanBlock 1.7.0  --
AI-Improvements-1.16.2-0.3.0.jar
AkashicTome-1.4-16.jar
AmbientSounds_v3.1.11_mc1.16.5.jar
appleskin-forge-mc1.16.x-2.2.0.jar
appliedenergistics2-8.4.3.jar
aquafied-1.0.2-build.6+mc1.16.5.jar
architectury-1.24.35-forge.jar
AttributeFix-1.16.5-10.1.3.jar
AutoRegLib-1.6-49.jar
BackTools-1.16.5-10.1.0.jar
bambooeverything-1.16.5-1.0.0-forge.jar
BetterDiving-1.16.5-1.3.2.jar
betterendforge-1.16.5-1.6.3.jar
blockcarpentry-1.16-0.4.0.jar
BloodMagic-1.16.4-3.1.5-25.jar
Blur-1.1.0-1.jar
Bookshelf-Forge-1.16.5-10.3.29.jar
Botania-1.16.5-419.jar
BotanyPots-1.16.5-7.1.27.jar
BotanyTrees-1.16.5-3.0.6.jar
BrandonsCore-1.16.5-3.0.11.238-universal.jar
buildinggadgets-1.16.5-3.8.2.jar
bwncr-1.16.5-3.10.16.jar
catalogue-1.3.0-1.16.5.jar
CBMultipart-1.16.5-3.0.2.120-universal.jar
cfm-7.0.0pre22-1.16.3.jar
charginggadgets-1.3.0.jar
Chisel-MC1.16.5-2.0.1-alpha.4.jar
chiselsandbits-0.3.4-RELEASE.jar
chocolate-1.3.0-1.16.4.jar
cloth-config-4.11.26-forge.jar
Clumps-6.0.0.27.jar
CobbleForDays-1.3.5.jar
CodeChickenLib-1.16.5-4.0.3.434-universal.jar
cofh_core-1.16.5-1.3.1.jar
CommonCapabilities-1.16.5-2.8.0.jar
compactmachines-4.0.0-beta.2.jar
configured-1.2.0-1.16.3.jar
constructionwand-1.16.5-2.4.jar
Controlling-7.0.0.27.jar
cottonly-0.7.8.jar
CraftingTweaks_1.16.5-12.2.1.jar
CreativeCore_v2.2.1_mc1.16.5.jar
CTM-MC1.16.1-1.1.2.6.jar
Cucumber-1.16.5-4.1.12.jar
culinaryconstruct-forge-1.16.5-4.0.0.6.jar
curios-forge-1.16.5-4.0.5.3.jar
CyclopsCore-1.16.5-1.12.1.jar
DeLogger-3.0.3-build.19+mc1.16.5.jar
Dimensional-Paintings-1.16.5-1.2.jar
Ding-1.16.5-1.3.0.jar
Draconic-Evolution-1.16.5-3.0.17.420-universal.jar
elevatorid-1.16.5-1.7.13.jar
emojiful-1.16.4-2.1.4.jar
EnderStorage-1.16.5-2.8.0.168-universal.jar
entangled-1.3.6-mc1.16.5.jar
ExtendedCrafting-1.16.5-3.1.9.jar
ExtraStorage-1.16.5-1.5.0.jar
extremeSoundMuffler-3.17_1.16.5.jar
FarmersDelight-1.16.5-0.4.6.jar
FastFurnace-1.16.4-4.4.0.jar
FastLeafDecay-v25.jar
FastWorkbench-1.16.4-4.5.1.jar
ferritecore-2.1.0-forge.jar
flatbedrock-1.2.0-build.2+mc1.16.5.jar
flowerseeds-1.16.5-1.3.2.jar
FluxNetworks-1.16.5-6.1.7.12.jar
ftb-backups-2.1.2.2.jar
ftb-chunks-forge-1605.3.2-build.81.jar
ftb-dripper-1605.1.0-build.16.jar
ftb-essentials-1605.1.5-build.32.jar
ftb-janitor-1605.1.2-build.12.jar
ftb-jar-mod-1605.1.0-build.31.jar
ftb-library-forge-1605.3.4-build.83.jar
ftb-power-pots-forge-1605.1.2-build.16.jar
ftb-quests-forge-1605.3.5-build.72.jar
ftb-ranks-1605.1.4-build.12-forge.jar
ftb-sluice-forge-1.0.10-build.37.jar
ftb-structures-1605.1.1-build.29.jar
ftb-team-islands-forge-1605-2.1-build.24.jar
ftb-teams-forge-1605.2.3-build.38.jar
ftb-ultimine-forge-1605.3.1-build.42.jar
ftbauxilium-forge-1605.1.1-build.14-forge.jar
glassential-forge-1.16.5-1.1.7.jar
gravestone-1.16.5-1.0.7.jar
harvest-1.16.3-1.0.3.jar
Hats-1.16.5-10.3.1.jar
IBICF-1.1.1-build.2+mc1.16.5.jar
iChunUtil-1.16.5-10.4.1.jar
ImmersiveEngineering-1.16.5-5.0.5-140.jar
industrial-foregoing-1.16.5-3.2.14.6-14.jar
IntegratedCrafting-1.16.5-1.0.20.jar
IntegratedDynamics-1.16.5-1.10.4.jar
integratednbt-1.16.4-1.4.2.jar
IntegratedTerminals-1.16.5-1.2.10.jar
IntegratedTunnels-1.16.5-1.8.7.jar
invtweaks-1.16.4-1.0.1.jar
ironchest-1.16.5-11.2.13.jar
item-filters-forge-1605.2.5-build.9.jar
itemcollectors-1.1.2-mc1.16.5.jar
JAGS-1.0.2-build.2+mc1.16.5.jar
jei-1.16.5-7.7.1.134.jar
jeiintegration_1.16.5-7.0.1.15.jar
JustEnoughProfessions-1.16.5-1.2.2.jar
JustEnoughResources-1.16.5-0.12.1.128.jar
Krate-1.16.5-0.1.4.jar
kubejs-blood-magic-1605.1.1-build.3.jar
kubejs-forge-1605.3.18-build.154.jar
kubejs-immersive-engineering-1605.1.1-build.2.jar
kubejs-mekanism-1605.1.2-build.2.jar
kubejs-thermal-1605.1.4-build.2.jar
kubejs-tinkers-1605.1.0-build.jar
kubejs-ui-forge-1605.1.4-build.12.jar
launchertray-1.0.jar
launchertray-progress-1.0.jar
lemonlib-1.3.6.jar
light-overlay-5.8.1.jar
Lollipop-1.16.5-3.2.9.jar
LostTrinkets-1.16.5-0.1.27.jar
Mantle-1.16.5-1.6.127.jar
mcjtylib-1.16-5.0.23.jar
mcw-bridges-2.0.0-mc1.16.5.jar
mcw-doors-1.0.3-mc1.16.5.jar
mcw-fences-1.0.1-mc1.16.5.jar
mcw-furniture-2.0.1-mc1.16.5.jar
mcw-paintings-1.0.2-mc1.16.5.jar
mcw-roofs-2.0.1-mc1.16.5-4.jar
mcw-trapdoors-1.0.3-mc1.16.5.jar
mcw-windows-2.0.0-mc1.16.5.jar
Mekanism-1.16.5-10.0.24.453.jar
MekanismGenerators-1.16.5-10.0.24.453.jar
MekanismTools-1.16.5-10.0.24.453.jar
minetogether-1.16.5-5.0.2-forge.jar
miniutilities-1.2.3.jar
mob_grinding_utils-1.16.5-0.4.30.jar
modnametooltip_1.16.2-1.15.0.jar
moredragoneggs-2.0.jar
Morpheus-1.16.5-4.2.70.jar
MouseTweaks-2.14-mc1.16.2.jar
MysticalAgradditions-1.16.5-4.2.2.jar
MysticalAgriculture-1.16.5-4.2.4.jar
MysticalCustomization-1.16.5-2.1.6.jar
NBT-Ingredient-Predicate-1.3.jar
notenoughwands-1.16-3.0.1.jar
ObsidianBoat-1.1.8-build.8+mc1.16.5.jar
Patchouli-1.16.4-53.2.jar
pipez-1.16.5-1.2.12.jar
pitg-1.16.5-2.0.1.jar
Placebo-1.16.5-4.6.0.jar
portable_stonecutter-1.16.5-1.3.5.jar
Powah-1.16.5-2.3.16.jar
ProjectRed-1.16.5-4.11.0-beta-0-core.jar
ProjectRed-1.16.5-4.11.0-beta-0-illumination.jar
ProjectRed-1.16.5-4.11.0-beta-0-integration.jar
ProjectRed-1.16.5-4.11.0-beta-0-transmission.jar
ReAuth-1.16-Forge-3.9.3.jar
recycler-1605.1.0-build.11.jar
refinedstorage-1.9.15.jar
refinedstorageaddons-0.7.3.jar
rftoolsbase-1.16-2.0.11.jar
rftoolsbuilder-1.16-3.1.2.jar
rftoolspower-1.16-3.0.9.jar
rftoolsstorage-1.16-2.0.13.jar
rftoolsutility-1.16-3.1.3.jar
rhino-forge-1605.1.5-build.73.jar
RoadRunner-mc1.16.5-1.3.0.jar
rsrequestify-1.16.5-2.1.4.jar
Scorge-3.1.3.jar
Seed Drop-1.16.5-2.1.1.jar
serverconfigupdater-1.3.jar
shutupexperimentalsettings-1.0.3.jar
SimpleDiscordRichPresence-1.16.4-1.3.5.jar
simplybackpacks-1.16.5-1.5.2-build.8.jar
SimplyJetpacks2-1.16.5-2.6.11.2.jar
simplylight-1.16.4-1.2.0-build.11.jar
smallships-1.16.5-1.10.3.jar
snad-1.0.9-forge.jar
SpawnerFix-1.16.2-1.0.0.2.jar
SquatGrow-1.0.11-build.11+mc1.16.5.jar
StorageDrawers-1.16.3-8.3.0.jar
StructureExpansion-1.16.5-1.0.7.jar
supermartijn642configlib-1.0.9-mc1.16.jar
supermartijn642corelib-1.0.12-mc1.16.5.jar
tconplanner-1.16.5-1.1.0.jar
TConstruct-1.16.5-3.2.0.290.jar
tesseract-1.0.24-mc1.16.jar
theoneprobe-1.16-3.1.4.jar
thermal_cultivation-1.16.5-1.3.0.jar
thermal_expansion-1.16.5-1.3.0.jar
thermal_foundation-1.16.5-1.3.2.jar
thermal_innovation-1.16.5-1.3.0.jar
thermal_locomotion-1.16.5-1.3.0.jar
time-in-a-bottle-1.1.0.jar
TipTheScales-1.16.5-3.0.0.15.jar
titanium-1.16.5-3.2.8.6-21.jar
Toast-Control-1.16.4-4.3.1.jar
ToolKit-2.0.0-build.1+mc1.16.5.jar
topaddons-1.16.5-2.1.5-beta.jar
torchmaster-2.3.8.jar
trashcans-1.0.10-mc1.16.5.jar
TrashSlot_1.16.3-12.2.1.jar
wyml-1.0.8-forge.jar
xnet-1.16-3.0.13.jar
XNetGases-1.16.5-2.3.7.jar

**Comment by quinelet** [comment]
options.txt sensitivity is about 0.5

**Comment by quinelet** [comment]
AHA! I figured it out. The mouse loop doesn't work at all if your framerate is set close to the tick rate (like mine is, on my laptop with intel graphics).

**Comment by quinelet** [comment]
So the mouse updates came through, but are being scaled down to zero on low-end setups like mine.

**Comment by quinelet** [comment]
probably something not so ideal about the partialFrames // getFrameTime() thing

**Comment by Meldexun** [comment]
Fixed in v1.16.5-1.3.4
