### ISSUE TITLE
Oxygen on other Planets using Beyond Earth

### ISSUE THREAD

**Issue by Boolyman** [Meldexun/BetterDiving#122]
**Enhancement**
Is it possible you could make your Oxygen system not conflict with Beyond-Earth's space oxygen system?  Your Oxygen system should not be active while the player is in space.  When the player is on another planet, your mod thinks they are in water, so it prevents the player from suffocating even though they should be using the air from their spacesuit, and suffocating once it depletes.  Beyond Earth is a popular mod, so I could see this being a problem in other packs as well.

https://www.curseforge.com/minecraft/mc-mods/better-diving

**Versions**
Better Diving: 1.16.5.1.3.4
Forge: 36.2.19
Minecraft: 1.16.5

**Other**
Singleplayer/Multiplayer:
Other mods (that are also installed): [Beyond Earth](https://www.curseforge.com/minecraft/mc-mods/beyond-earth)

**Comment by Meldexun** [comment]
I don't know what you mean. Works fine for me.

**Comment by Boolyman** [comment]
I have tested this in a vanilla world, with only Better Diving and Beyond Earth, with basic settings, and it does not work fine.

Are you saying that you tested going to a planet from the Beyond Earth mod, wore their spacesuit for oxygen, and when your Oxygen reached zero, you actually took damage?  Because that is not the same result I get.  When I am wearing a space suit, and my oxygen hits zero, while your mod is installed, nothing happens... I don't take suffocation damage or anything like that.  When I disable your oxygen system, the Beyond Earth oxygen system works as intended... the player takes suffocation damage.

Your oxygen bar is only supposed to show up when the player is in water.... if there is no conflict, why does it show up on the GUI any time a player is in space?

**Comment by Meldexun** [comment]
I see what you mean. The mod is relying on vanilla values and their oxygen system overall is kind of yanky. So there is nothing for me to fix here.
