### ISSUE TITLE
Crash on multiplayer server

### ISSUE THREAD

**Issue by Boolyman** [Meldexun/BetterDiving#123]
**Describe the bug**
https://paste.gg/p/anonymous/70729f8652b84e04b731b84050308cc6

**To Reproduce**
1. I don't know what caused the crash.
2. See crash report

**Versions**
Better Diving: 1.16.5-1.3.4
Forge: 36.2.23
Minecraft: 16.16.5

**Other**
Crash report (if one exists):  https://paste.gg/p/anonymous/70729f8652b84e04b731b84050308cc6
Singleplayer/Multiplayer: Multiplayer

**Comment by Meldexun** [comment]
The crash report just says that a single tick took longer than 60 seconds (this limit can be increased in the server settings). But there is no indication that this is caused by BetterDiving.
It could be any mod or mod combination.
