### ISSUE TITLE
seamoth can be in "space"?

### ISSUE THREAD

**Issue by segev1708** [Meldexun/BetterDiving#124]
What ?
space?
![image](https://user-images.githubusercontent.com/98040924/151651610-765c50e5-e2c7-4ad6-bbb1-107a7c483ff6.png)

Better Diving:1.5.8
Forge:8.0.99.99
Minecraft:1.12.2

Multiplayer
other mods/modpack:R.A.D TiC Edition

**Comment by Meldexun** [comment]
This is just the description from the seamoth from subnautica. There is no way to use a seamoth in space.
