### ISSUE TITLE
Config changes are STILL being ignored.  

### ISSUE THREAD

**Issue by Boolyman** [Meldexun/BetterDiving#125]
**Describe the bug**
The config is still being ignored.   I turned all booleans for ore outcrops to FALSE so they would stop spawning... but they still do.

**To Reproduce**
1. Turn ore spawn "enabled" boolean to False.
2. Generate a new world.
3. Be shocked and disappointed when there are still ore outcrops generating.

**Versions**
Better Diving: 1.16.5-1.3.4
Forge: 36.2.23
Minecraft: 1.16.5

**Other**
Crash report (if one exists):
Latest log:
Singleplayer/Multiplayer:
Other mods (that are necessary to produce the bug):
Other mods (that are also installed):

**Comment by Meldexun** [comment]
It looks like only the ore `enabled` config options are not working. All other config options should work fine (Note that setting the chance to `0` does not disable generation).

**Comment by Meldexun** [comment]
Fixed in v1.16.5-1.3.5
