### ISSUE TITLE
Dragon Survival Oxygen Meter

### ISSUE THREAD

**Issue by mpevner** [Meldexun/BetterDiving#127]
If using the dragon survival mod, Water dragons have an "inverted" oxygen system - they have limited air when on land. If Dragon Survival and Better Diving are installed, water dragons no longer have an oxygen meter when on land.

**To Reproduce**
Become a water dragon via Dragon Altar (Dragon Survival), note lack of oxygen meter when on land. 

**Versions**
Better Diving: 1.3.4
Dragon Survival: 0.9.2
Forge: 36.2.20
Minecraft: 1.16.5

**Comment by Meldexun** [comment]
Fixed in v1.16.5-1.3.5
