### ISSUE TITLE
Oxygen GUI is not disabled when config is set to disable it

### ISSUE THREAD

**Issue by xkforce** [Meldexun/BetterDiving#15]
Simply the Oxygen GUI/functionality is not disabled when the config is set to disable it.

**Comment by Meldexun** [comment]
I'm currently busy so it will take same time until i look at the issue

**Comment by Meldexun** [comment]
Ok i have now tested it and everything seems to work fine. What did you change in the config?

**Comment by xkforce** [comment]
Here is the config: https://pastebin.com/szvFPwC8

I really just wanted to use the diving movement mechanic and the new underwater vision.  I wanted vanilla to be handling the bubble meter and everything else.  But while the diving equipment etc. have been disabled, the Oxygen GUI is still there instead of the vanilla bubble meter.

**Comment by Meldexun** [comment]
Try in the 07 - oxygen gui category to set the customOxygenGui to 0.

**Comment by xkforce** [comment]
That worked.  I didn't change that particular option because I assumed that since the module it's in was disabled that it was redundant.

**Comment by Meldexun** [comment]
Well it was a bug. I just gave you a fast solution. Will be fixed in future.
