### ISSUE TITLE
Obsidian breaking speed is way too fast

### ISSUE THREAD

**Issue by MatthiasMann** [Meldexun/BetterDiving#16]
I'm using BetterDiving-1.12.2-1.3.54 and an IC2 diamond drill and wearing the wetsuit leggings (20% increase).

When standing in 1 block of water (so that vanilla Minecraft would not count you as under water) you can break obsidian nearly instantly (~1 second) while out of water it takes a lot longer (~6 seconds).

**Comment by Meldexun** [comment]
Should be fixed in v1.3.60.
