### ISSUE TITLE
add zh_cn.lang

### ISSUE THREAD

**Issue by EdgewalkerBlue** [Meldexun/BetterDiving#17]
itemGroup.tab_better_diving=更好的潜水

item.diving_mask.name=潜水面罩（常规）
item.standard_o2_tank.name=氧气罐（常规）
item.wetsuit_leggings.name=潜水服护腿（常规）
item.fins.name=脚蹼（常规）

item.rebreather.name=潜水面罩（改进的）
item.high_capacity_o2_tank.name=氧气罐（高容量）
item.improved_wetsuit_leggings.name=潜水服护腿（改进的）
item.ultra_glide_fins.name=脚蹼（超滑）

item.reinforced_diving_mask.name=潜水面罩（加强）
item.reinforced_o2_tank.name=氧气罐（加强）
item.reinforced_wetsuit_leggings.name=潜水服护腿（加强）
item.reinforced_fins.name=脚蹼（加强）

item.diving_mask.tooltip=需要使用氧气罐潜水
item.standard_o2_tank.tooltip=增加潜水时间约 %d 秒
item.wetsuit_leggings.tooltip=增加水下速度约 %d%%
item.fins.tooltip=游泳速度提高约 %d%%

item.rebreather.tooltip=在深度超过30米的情况下以正常效率潜水%s需要使用氧气罐潜水
item.high_capacity_o2_tank.tooltip=增加潜水时间约 %d 秒
item.improved_wetsuit_leggings.tooltip=增加水下速度约 %d%%
item.ultra_glide_fins.tooltip=游泳速度提高约 %d%%

item.reinforced_diving_mask.tooltip=潜水需要氧气罐 %s比常规潜水装备获得更多的保护
item.reinforced_o2_tank.tooltip=增加潜水时间约 %d 秒 %s比常规潜水装备获得更多的保护
item.reinforced_wetsuit_leggings.tooltip=增加水下速度 %d%% %s比常规潜水装备获得更多的保护
item.reinforced_fins.tooltip=游泳速度提高约 %d%% %s比常规潜水装备获得更多的保护

tile.limestone_outcrop.name=裸露的石灰石
tile.sandstone_outcrop.name=裸露的砂岩
tile.creepvine.name=苦力怕藤样品
tile.seagrass.name=海草
tile.acid_mushroom.name=酸蘑菇

item.titanium.name=钛矿石
item.copper_ore.name=铜矿石
item.silver_ore.name=银矿石
item.lead.name=铅矿石
item.gold.name=金矿石
item.titanium_ingot.name=钛锭
item.wiring_kit.name=绕线盒
item.battery.name=电池
item.power_cell.name=能量核心
item.creepvine_seed_cluster.name=苦力怕藤种子群
item.silicone_rubber.name=硅橡胶
item.fiber_mesh.name=纤维网
item.lubricant.name=滑润剂

item.seamoth.name=潜水艇（海蛾号）
entity.entity_seamoth.name=潜水艇（海蛾号）

**Comment by Meldexun** [comment]
I've added a chinese translation in v1.3.56.
