### ISSUE TITLE
NPE

### ISSUE THREAD

**Issue by wormzjl** [Meldexun/BetterDiving#18]
https://gist.github.com/wormzjl/deeeaf1cb9c0c41b499f923369262911
Seems to happen when I get off the seamoth

**Comment by Meldexun** [comment]
So i really don't know how you got this crash report after testing it multiple times. I mean i also get a crash but a completly different error. But i think the reason is the same and i'm working on it.

**Comment by Meldexun** [comment]
Should be fixed in v1.3.60.
