### ISSUE TITLE
No Problem only a Question with pictures!!!

### ISSUE THREAD

**Issue by Titoo8899** [Meldexun/BetterDiving#22]
hi,
I have only 2 questions. One in the down right of the picture is a sunny behind the DynamicStealth Mod GUI. Question one: Is this Light GUI behind the GUI of DynamicStealth from your mod?
Question two: Then this GUI from your mod is, give it a way to move the position of the GUI to a other place of the Minecraft Window. Downleft or so?
And last question: That is the function of this GUI? Then I swim lower and lower then will the light bar % go down.

![2019-07-01_19 18 49](https://user-images.githubusercontent.com/42325138/60454993-947e0f80-9c35-11e9-917f-46dcbae8a20a.png)
![2019-07-01_19 19 02](https://user-images.githubusercontent.com/42325138/60454994-947e0f80-9c35-11e9-8af3-6f9202666d8a.png)
![2019-07-01_19 19 06](https://user-images.githubusercontent.com/42325138/60454995-947e0f80-9c35-11e9-935b-7773114054f9.png)

**Comment by Meldexun** [comment]
No, that sun gui isn't from my mod. So i also don't know what it's doing or how to move it.
