### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Arctic90x** [Meldexun/BetterDiving#23]
When you go into Spectator Mode it is super glitchy with is mod running

**Comment by Meldexun** [comment]
What do you mean with "super glitchy"?

**Comment by Arctic90x** [comment]
Like it's not super, glitchy but it does make it hard to move around and check out your world if you want to go into Spectator Mode. My bad on saying "Super" but it is kinda bad still.

**Comment by Meldexun** [comment]
I'm sorry but i still don't understand what your problem is. Please describe what is happening. Because i just tested it and Spectator Mode seems to work normal.

**Comment by Arctic90x** [comment]
May I ask what version, forge you have on and if you're running any other
mods with it? I'll test it again and see if it works fine without any mods
maybe something is clashing, I know I was in the mining world from the
mod *Aroma1997s
Dimensional World*
when it was a bit glitchy for me. Link is here
https://www.curseforge.com/minecraft/mc-mods/aroma1997s-dimensional-world

**Comment by Meldexun** [comment]
I'm always testing with latest Forge (1.12.2 - 14.23.5.2838) and without any other mods.

**Comment by Arctic90x** [comment]
I did learn what the problem was and it was not your mod. I am very sorry
and I apologize for the inconvenience, come to find out it was the
BetterSwiming mod.
