### ISSUE TITLE
Changing ore dictionary entries

### ISSUE THREAD

**Issue by Deightine** [Meldexun/BetterDiving#25]
This is a really cool mod. I'm looking forward to seeing where you take it.

1. I noticed your titanium is registered with 'oreTitanium', but your titanium ingots are not tagged for 'ingotTitanium'. It is literally the only thing not allowing complete cross-compatibility for some mods. Techguns for example.

2. I also noticed that you recently configured the GUI to play nice with ToughAsNails. Which is great because the themes work well together. But right now the diving gear isn't offering any cold protection despite the gear looking like a full wet suit. Any chance of adding that? Even if its just 1 point of cold resist per item (equivalent to the wool clothing), it'll help offset the fact that being wet is a pretty heavy penalty. It can be done manually, but if you're already looking at TAN it'd be a great cross-compatibility selling point.

Thanks for your work. A good diving mod has been needed for a long while.

**Comment by Meldexun** [comment]
I'm glad you like my mod.

1. The problem with the titanium ingot is that it is crafted from 9 titanium and that would be more equal to an titanium block. So i'm thinking of registering my titanium as 'oreTitanium' and 'ingotTitanium' and my titanium ingot as 'blockTitanium'.

2. I also thought about adding some TAN compatibility. But i more thought of the seamoth adding complete protection against the wetness penalty. I will see what i can do there.

**Comment by Deightine** [comment]
If it's more a matter of the investment, you could always make the titanium item needed for the seamoth a non-ingot. Something like 'titanium shell' or similar. Then it would be the product of titanium. That way your current titanium registration would still be 'fair' when compared to other mods.

The reason I suggested TAN warmth for the clothing is that the seamoth is your 'top of the tree' item right now. But getting what you need for it means going into the water and going into a deep ocean tile can be lethal within the time span of a breath with Better Diving on.

So even if the items only offered +1 each (total of 4 with a set), that would only slow down the hypothermia but not stop it. Then you could put a temperature control ability on seamoth. There is a bauble in Tough Expansion that does temperature regulation you could probably peek at the code for to see how that's done.

**Comment by Meldexun** [comment]
I won't add ToughAsNails warmth because that can be done in the ToughAsNails config.

**Comment by Meldexun** [comment]
1.12 isn't worked on anymore.
