### ISSUE TITLE
Diving issue

### ISSUE THREAD

**Issue by Georg255** [Meldexun/BetterDiving#26]
Not sure if it's your mod or another mod messing with it but whenever I die and go to swim again, character just freezes.  Can't move or anything and the o2 meter is permanently set at 0 so I die again.  This issue disappears when I go to title screen and reload the save rather than respawn.

**Comment by Meldexun** [comment]
So i tested it and it is my mod. Still i would appreciate it if you could try to reproduce the bug with only my mod installed before opening an issue.
But until i release a bug fix you can equip an item (helmet, chestplate, leggings or shoes) after dieing. It can be any armor item and you can unequip it instantly. That would be faster than going to the main menu.

**Comment by Georg255** [comment]
OK.

**Comment by Meldexun** [comment]
Fixed in v1.3.81.
