### ISSUE TITLE
Compatability with Metamorph: Water breathing from morph is ignored

### ISSUE THREAD

**Issue by MattKaboom** [Meldexun/BetterDiving#28]
Custom Oxygen doesn't respect metamorph underwater breathing ability (1.12.2)

**Comment by Meldexun** [comment]
Since the metamorph mod isn't in real development anymore i won't invest much time to find a fix. But i will still try to fix it. It just takes long if there isn't an easy fix.

**Comment by ChrisLTheNerd** [comment]
I don't have to much experience programming, but can't you fix it by making the better diving mod check for morph mods, then make it check for water breathing abilities, and give control over to the morph mod if water breathing abilities are present, or contact a creator from meta morph on advise.  But what you do is your choice and i'll respect it :)

**Comment by Meldexun** [comment]
Fixed in v1.5.0
