### ISSUE TITLE
Disabling Creepvine Seed Clusters

### ISSUE THREAD

**Issue by kriNon** [Meldexun/BetterDiving#30]
Hey,
Was wondering if there's any chance you could add a config option to disable the generation of creepvine seed clusters? Was wanting to disable them for a modpack I'm working on.

Thanks :)

**Comment by Meldexun** [comment]
Maybe i will add a config option for that. But the next update is a bigger one and still needs some time.

**Comment by Meldexun** [comment]
Added in v1.4.03. (May be changed in future versions)
