### ISSUE TITLE
Can you add more fish creatures？

### ISSUE THREAD

**Issue by Abo233** [Meldexun/BetterDiving#31]

**Comment by Abo233** [comment]
I feel  that something is missing

**Comment by Meldexun** [comment]
I'm already working on mobs. With the next big update i want to naturally spawn various small fishes. (Maybe also a beta version of a lovely big one)

**Comment by Meldexun** [comment]
Added 5 fish (peeper, bladderfish, garryfish, holefish, boomerang) in v1.4.0

**Comment by Abo233** [comment]
Nice！
---原始邮件---
发件人:"Meldexun"<notifications@github.com>
发送时间:2019年10月12日 星期六 上午7:56
收件人:"Meldexun/BetterDiving"<BetterDiving@noreply.github.com>
抄送:"Abo233"<1492956011@qq.com>;"Author"<author@noreply.github.com>
主题:Re: [Meldexun/BetterDiving] Can you add more fish creatures？ (#31)

Closed#31.

&mdash;
