### ISSUE TITLE
Incompatibility with Idō

### ISSUE THREAD

**Issue by Stormister** [Meldexun/BetterDiving#34]
When this mod and Idō are installed together, this mod overrides all of Idō's behavior due to both influencing how swimming is handled.

**To Reproduce**
1. Install both BetterDiving and Idō (https://www.curseforge.com/minecraft/mc-mods/ido)
2. Go into water.
3. Go into 3rd person
4. See that Idō's behavior does not work (the character model is still standing upright, 2 blocks tall, when it should be 1 block tall, horizontal)

**Versions**
Better Diving: 1.3.91
Idō: 1.0.4
Forge: 14.23.5.2838
Minecraft 1.12.2

**Other**
Other mods (that are necessary to produce the bug): Idō (https://www.curseforge.com/minecraft/mc-mods/ido)

A side note: The creator of Idō has said that this is not on his side, but he is willing to cooperate to make the two mods compatible.

**Comment by Meldexun** [comment]
I'm not able to reproduce the bug. I installed the 2 mods, went into water and started sprinting. The player was rotated. It may be another mod that you have installed.

**Comment by Stormister** [comment]
> I'm not able to reproduce the bug. I installed the 2 mods, went into water and started sprinting. The player was rotated. It may be another mod that you have installed.

Wow I feel like an imbecile. I forgot you need to sprint to do it. Please excuse my idiocy.
