### ISSUE TITLE
Compatability for the "Streams" mod?

### ISSUE THREAD

**Issue by Abo233** [Meldexun/BetterDiving#35]
Lead to streams mod

I feel the water a little science

Under the waterfall will not be washed away。。

**Comment by Meldexun** [comment]
Currently i'm not working on compatability.
Link to the mod: [Streams](https://www.curseforge.com/minecraft/mc-mods/streams)

**Comment by Meldexun** [comment]
I don't understand what the problem is. When testing both mods together it seems to work fine. So unless someone can show me a problem with the streams mod i will close this.
