### ISSUE TITLE
Fog Bug when I go underwater and  out of the water with the newest Version

### ISSUE THREAD

**Issue by Titoo8899** [Meldexun/BetterDiving#36]
Hi,
with your newest 1.12.2 Version give it a bug with the Fog. Then I go underwater and go out the Fog was on then I go out of water. In your mod is it only in the under the Water but your mod must be compatible make with the Mod "NoFog".  Please check the Pictures.
I have Your BetterDiving Mod, NoFog Mod, Smooth Light Mod and other Dekoration and Items mod. But the Person of Smooth Light say it is a Problem of your mod. Not a Problem of NoFog mod only a mod bug in your mod. Please check this and fix it.
![2019-09-22_16 14 16](https://user-images.githubusercontent.com/42325138/65391615-7c68e880-dd6b-11e9-9ca8-a085773b7f74.png)
![2019-09-22_16 52 32](https://user-images.githubusercontent.com/42325138/65391616-7c68e880-dd6b-11e9-8c6f-ba6e3fb78614.png)

Picture 1 show behind I was in the Water the World is with Fog and I have Visibility of 11. And Picture 2 show before I was in the water. The World have with NoFog a clear world.

**Comment by Titoo8899** [comment]
Pleae check this and find a fix.

**Comment by Titoo8899** [comment]
I have test and the Fog what we have with your mod underwater go not out then we are out of water I have testet with your mod and the NoFog mod. Please fix this and make a Fog fix.

**Comment by Meldexun** [comment]
You can disable fogDensity inside 07 - Client Settings of the config. (requires restart)
