### ISSUE TITLE
outcrops not dropping ores

### ISSUE THREAD

**Issue by ArMoReDfUrY** [Meldexun/BetterDiving#38]
**Describe the bug**
breaking outcrops with or without tools drops no items at all

**To Reproduce**
1. Go to 'an outcrop and break it.
2. Use item 'any/none
4. See error no error log sorry just no resulting items

**Versions**
Better Diving: 1.12.2-1.4.0
Forge: forge-1.12.2-14.23.5.2847
Minecraft 1.12.2

**Other**
Crash report (if one exists): none srry
Other mods (that are necessary to produce the bug):
it is a big list. however i did roll back to the previous version (BetterDiving-1.12.2-1.3.91)  and outcrops work as intended.
to test this i spawned a line of 10 limestone outcrops & 10 sandstone outcrops (i did this in both versions).
i had also tested the world generated outcrops, they work in BetterDiving-1.12.2-1.3.91
but not in Better Diving 1.12.2-1.4.0

thanks for your time. BTW awesome mod it has become a instant addition to all my packs.

**Comment by Meldexun** [comment]
I found the bug. There will be an update in a few hours. I'm just waiting a bit to see if there are any other bugs in the newest version.

**Comment by ArMoReDfUrY** [comment]
thanks for the quick fix. looking forward to it :)

**Comment by Meldexun** [comment]
I had to do something else but in 10-12 hours the update will be out.

**Comment by ArMoReDfUrY** [comment]
all good , I'm happy to wait as long as is needed. 
take your time ;)

**Comment by Meldexun** [comment]
Fixed in v1.4.01
