### ISSUE TITLE
Dimension Spawn Configs

### ISSUE THREAD

**Issue by DVorriose** [Meldexun/BetterDiving#39]
**Enhancement**
Would you consider adding a dimension whitelist and/or blacklist to spawning configs?  Especially for fish.  They're great!  Would love to have them in a separate water world....

**Versions**
Minecraft: 1.12.2

**Comment by ArMoReDfUrY** [comment]
that would be very handy.

**Comment by Meldexun** [comment]
Added in v1.4.10
