### ISSUE TITLE
The mask is duplicated on the abdomen

### ISSUE THREAD

**Issue by kellixon** [Meldexun/BetterDiving#4]
MC 1.12.2. BetterDiving 1.0.4. The mask is duplicated on the abdomen.
![2019-01-04_09 48 52](https://user-images.githubusercontent.com/22012731/50676548-facb0200-1005-11e9-9039-9b9b59dc4e48.png)

**Comment by Meldexun** [comment]
I think you tried reequipping the armor or restarting the game. So is it a singleplayer game or server?

**Comment by kellixon** [comment]
Singleplayer. Just look the items out of creativity when tested. Oddly, it appears not every time. Now everything is fine)
