### ISSUE TITLE
Server Startup Crash w/ 1.4.03

### ISSUE THREAD

**Issue by nephatrine** [Meldexun/BetterDiving#41]
**Describe the bug**
The new version of Better Diving crashes dedicated server on startup. Looks like it's trying to use a clientside audio class. Version 1.4.02 works.

**Versions**
Better Diving: BetterDiving-1.12.2-1.4.03
Forge: forge-1.12.2-14.23.5.2838

**Other**
Crash report: https://pastebin.com/Px4ef4MF

**Comment by Meldexun** [comment]
Thank you for reporting. Should be fixed in v1.4.04.
