### ISSUE TITLE
Diving Gear display issues on armor stand.

### ISSUE THREAD

**Issue by netmc** [Meldexun/BetterDiving#42]
**Describe the bug**
The diving helmet always faces south no matter which direction the armor stand is placed.  

The armor plays animations while on the armor stand (arms move).

**To Reproduce**
Place diving gear on armor stand

**Versions**
Better Diving: 1.4.01
Forge: 14.23.5.2847
Minecraft 1.12.2

**Comment by Meldexun** [comment]
I have a fix though i won't release an update with it soon because it's just a minor visual issue.

**Comment by Meldexun** [comment]
Fixed in v1.4.10
