### ISSUE TITLE
Crash when populating world with low sea level

### ISSUE THREAD

**Issue by Zack7292** [Meldexun/BetterDiving#44]
**Describe the bug**
my game simply crash when i was looking around

**To Reproduce**
idk it happen without me doign anything

**Versions**
Better Diving: 1.4.10
Forge: 2847
Minecraft: 1.12.2

**Other**
Crash report (if one exists): https://paste.dimdev.org/ikazomikut.mccrash
Other mods (that are necessary to produce the bug): (in the crash report bcs there much)

**Comment by Meldexun** [comment]
Fixed in v1.4.11

**Comment by Zack7292** [comment]
Thx :)
