### ISSUE TITLE
Random Crashes in Other Dimensions

### ISSUE THREAD

**Issue by Jackiecrazy** [Meldexun/BetterDiving#45]
**Describe the bug**
I was in AoA's Lunalus and it keeps randomly crashing...

**To Reproduce**
1. Go to Lunalus?
2. Wait around. No specific time frame of appearance.

**Versions**
Better Diving: 1.4.11
Forge: 14.23.5.2847
Minecraft 1.12.2

**Other**
Crash report (if one exists):https://paste.dimdev.org/poqozuhomi.mccrash
Other mods (that are necessary to produce the bug): advent of ascension

**Comment by Meldexun** [comment]
How often did it crash? And did it also happen in other dimensions?

**Comment by Jackiecrazy** [comment]
Maybe once per 5 minutes? And yes it happens in pretty much every dimension I visited. Didn't check nether or end, though.

**Comment by Jackiecrazy** [comment]
Ah, it just happened in the overworld.

**Comment by Meldexun** [comment]
Should be fixed in v1.4.13
