### ISSUE TITLE
Compatibility with TerraFirmaCraft

### ISSUE THREAD

**Issue by Pentasis** [Meldexun/BetterDiving#46]
**Enhancement**
Let underwater plants spawn in tfc:ocean and tfc:deep_ocean biomes.

**Versions**
Minecraft: 1.12.2

I added these biomes to the config and raised the height to accomodate tfc-terrain, but only the fish spawn, not the plants. This could be either related to the fact that TFC uses different water-blocks or gravel/sand-blocks?)

**Comment by Meldexun** [comment]
I could try to add compatability but the problem is that the TerraFirmaCraft water destroys my blocks.

**Comment by Pentasis** [comment]
Well, if it is too much work don't bother. It is a bit of a niche case. I can live without it :)

**Comment by Meldexun** [comment]
Fixed in v1.5.0
