### ISSUE TITLE
Unable to place seamoth on server

### ISSUE THREAD

**Issue by Mikecolle** [Meldexun/BetterDiving#47]
im running the most recent version of better diving and forge on minecraft 1.12.2 and im unable to place a seamoth. is the something im missing? ive tried right clicking it everywheres, in water underwater, 1 block deep water etc...

**Comment by Meldexun** [comment]
I just tested it and everything worked. Just right click with the seamoth and it should be placed in the world.

**Comment by Mikecolle** [comment]
im playing with the technical adventuring pack with it given through creative, would this cause any issues

**Comment by Meldexun** [comment]
No. Are you playing on a server?

**Comment by Mikecolle** [comment]
yes

**Comment by Meldexun** [comment]
Make sure to have the same version of Better Diving installed on the server and on the client.

**Comment by Mikecolle** [comment]
both are running BetterDiving-1.12.2-1.4.04

**Comment by Meldexun** [comment]
Then try updating the mod.

**Comment by Mikecolle** [comment]
cool i found a bug lmao

**Comment by Meldexun** [comment]
Fixed in v1.4.13
