### ISSUE TITLE
world crash

### ISSUE THREAD

**Issue by Fenix711** [Meldexun/BetterDiving#48]
swimming around in the water in spectator mode exploring new world gen with quite a few mods installed.
not able to be reproduced.
vanillafix report: https://paste.dimdev.org/enufehesis.mccrash
crash report: https://pastebin.com/pdKWHbbM
![2019-11-29_11 31 30](https://user-images.githubusercontent.com/29525146/69881708-d5895700-129b-11ea-9bfc-7f963c4b4593.png)

**Comment by Fenix711** [comment]
sitting in this position for a while while in spectator causes crash again.
https://paste.dimdev.org/nuqozuracu.mccrash
https://pastebin.com/yi7bqEnc

**Comment by Meldexun** [comment]
Fixed in v1.4.14
