### ISSUE TITLE
Vampirism Integration

### ISSUE THREAD

**Issue by Fenix711** [Meldexun/BetterDiving#49]
**Enhancement**
When Better Diving and Vampirism are installed together there is a UI issue that shows the breathing bubbles over the bar until the player reloads(single player) or relogs.(server)
The ideal scenario would be that if a player were to be a vampire, the effects from better diving do not persist in anyway. (or as you see fit) and then for hunters they have the normal effects of Better Diving

**Versions**
Minecraft: 1.12.2

**Other**
Other mods:
Vampirism

**Comment by Meldexun** [comment]
I don't understand what you mean with your first part. What bubbles over what bar? Please explain that further.
And why should vampires not be effected by Better Diving?

**Comment by Meldexun** [comment]
Because vampires don't drown in vanilla Vampirism as of v1.4.14 they don't drown with Better Diving.
