### ISSUE TITLE
Description of items

### ISSUE THREAD

**Issue by kellixon** [Meldexun/BetterDiving#5]
Add in .lang description of items.
![2019-01-04_09 50 55](https://user-images.githubusercontent.com/22012731/50676608-539a9a80-1006-11e9-9065-a5082f084268.png)

**Comment by Meldexun** [comment]
I knew that you would like to have that :)
I'm working on it but I have to find a way to insert the numbers the right way.

**Comment by Meldexun** [comment]
That would be the new en_US.lang file. You probably want to translate it. [https://pastebin.com/6Kvn3DD9](https://pastebin.com/6Kvn3DD9)

**Comment by kellixon** [comment]
pls)) ru_ru.lang - https://pastebin.com/baeSruTr

**Comment by Meldexun** [comment]
added with v1.0.5
