### ISSUE TITLE
Creepvine seed clusters aren't consumed

### ISSUE THREAD

**Issue by pcal43** [Meldexun/BetterDiving#50]
I love the mod - thanks for all of your work on it.

I really like the illumination that the creepvines provide.  But one (very minor) thing that bugs me is that, because the seeds are unlimited use, it's almost too easy to grow them.  

Seems like it would be better if it worked something more like regular wheat: harvesting a seed cluster should give me (say) 3-5 seeds that are single-use.  I'm not sure exactly what the number should be since it seems that not all plants generate a seed cluster.  But you get the idea.

Anyway, it's a very minor thing in the grand scheme.  I really really like what you did here - thanks!

**Comment by Meldexun** [comment]
It's a bug. Seeds should be consumed when using them.

**Comment by pcal43** [comment]
Got it, thanks!  And sorry for not using the template.

**Comment by Meldexun** [comment]
Fixed in v1.5.0

**Comment by pcal43** [comment]
awesome, thanks!
