### ISSUE TITLE
crashlog with ic2 classic

### ISSUE THREAD

**Issue by trilexcom** [Meldexun/BetterDiving#51]
**Describe the bug**

client crashes when you diving into water and come back out

**To Reproduce**
1. Go to. jump into water and get out .
.
.
.

https://gist.github.com/trilexcom/44838fb804d4be24d7e70bd3933e279b

**Versions**
Better Diving: 1.12.2-1.4.14
Forge: 2847
Minecraft: 1.12.2

**Other**
Crash report (if one exists): https://gist.github.com/trilexcom/44838fb804d4be24d7e70bd3933e279b
Singleplayer/Multiplayer: both
Other mods (that are necessary to produce the bug): ic2 classic
Other mods (that are also installed):

**Comment by Meldexun** [comment]
A smaller update should come out soon and fix this.

**Comment by Meldexun** [comment]
Fixed in v1.5.0
