### ISSUE TITLE
The Textures should be reworked.

### ISSUE THREAD

**Issue by theStrobilus** [Meldexun/BetterDiving#52]
I just took a look at the mod only a few minutes ago from writing this post, and, it's great! Except, the textures sort of throw me off. While it is technically possible for resourcepacks to exist, it would be nice and convenient to already have a set of good textures. The worst offenders (in my opinion) are the fish item(s) and the titanium ingot.

I know this is a pretty minor issue, but, if possible, please change them. 

**Versions**
Better Diving: 1.4.14
Forge: 2847
Minecraft: 1.12.2

**Comment by Meldexun** [comment]
It's pretty clear that i'm not a great artist. Especially i have some problems with textures. So that probably won't change unless i have an artist which does that (though i'm not sure if i want to work with another person on this mod).
