### ISSUE TITLE
Biome Bundle Incompatibiliy

### ISSUE THREAD

**Issue by Pengu-Hunter** [Meldexun/BetterDiving#55]
**Describe the bug**
If you load better diving and biome bundle then all of diving's world gen and mobs spawn except creepvine.

**To Reproduce**
1. Load better diving and biome bundle

**Versions**
Better Diving: 1.4.14
Forge: 14.23.5.2847
Minecraft: 1.12.2

Latest log:
Singleplayer/Multiplayer: Single
Other mods (that are necessary to produce the bug): Biome Bundle

**Comment by Meldexun** [comment]
The default config of v1.4.14 sets the maxHeight of creepvine to 40 but biome bundle has no deep oceans (seafloor >40) and so no creepvine generates. You can just change the config (up to 14 blocks tall creepvines may spawn).
