### ISSUE TITLE
Creepvine Cluster Crash

### ISSUE THREAD

**Issue by MineWiz270** [Meldexun/BetterDiving#56]
**Describe the bug**
Game keeps crashing whenever trying to harvest creepvine clusters

**To Reproduce**
1. Break Creepvine Cluster
.
.
.
2. Crash

**Versions**
Better Diving: 1.4.14
Forge: 14.23.5.2847
Minecraft: 1.12.2

**Other**
Crash report (if one exists): https://paste.dimdev.org/lanacemaro.mccrash

Latest log: 
Singleplayer/Multiplayer: Singleplayer
Other mods (that are necessary to produce the bug): WIT (What is That)
Other mods (that are also installed):

**Comment by Meldexun** [comment]
The next update should come soon and will fix this.

**Comment by Meldexun** [comment]
Fixed in v1.5.0
