### ISSUE TITLE
Exception in server tick loop &  Batching chunks

### ISSUE THREAD

**Issue by RodrigoTaipe93** [Meldexun/BetterDiving#57]
There seems to be an issue between:

- Farseek & Better Diving. I'm reporting both authors about the issue:

- https://paste.ee/p/nLmZR

- https://paste.dimdev.org/evuwovebof.mccrash

**Comment by Meldexun** [comment]
In the next update this is (hopefully) fixed. The update should come out soon.

**Comment by Meldexun** [comment]
Fixed in v1.5.0
