### ISSUE TITLE
You can add more  aquatic monster？

### ISSUE THREAD

**Issue by Abo233** [Meldexun/BetterDiving#58]
1.The shark（social）
2.The crocodile（social）
3.Water ghost
4.Toxic jellyfish
5.piranha（social）

Thanks you!

**Comment by Meldexun** [comment]
This mod focuses more on diving mechanics and features from subnautica. So i won't add "normal" mobs. Also there are plenty other mods that add aquatic mobs like sharks, piranhas, etc. to the game.
