### ISSUE TITLE
Many unnecessary lines in the log

### ISSUE THREAD

**Issue by kellixon** [Meldexun/BetterDiving#6]
MC 1.12.2. BetterDiving 1.0.6.
There is the possibility of adding a config to disable debug information. Half an hour sailed in the sea and about 150 000 lines
![0](https://user-images.githubusercontent.com/22012731/50985770-338f3d80-1516-11e9-96bc-439150791e45.jpg)

**Comment by Meldexun** [comment]
I always forget to remove it... In next update there will be a config option so you won't see it.

**Comment by kellixon** [comment]
Thanks!
