### ISSUE TITLE
[Enhancement] Armor makes you drown

### ISSUE THREAD

**Issue by pimalel233** [Meldexun/BetterDiving#60]
**Enhancement**
Armor pieces could make you drown, you would be forced to swin with the swimming equipment or wihout any armor. There could be expensive enhantements that could make you swim with specific armor pieces.

**Versions**
Better Diving: any upcoming 1.12.2 version
Forge: any
Minecraft: 1.12.2

**Comment by Meldexun** [comment]
I can understand why you may want something like that. But i still don't like it. The main goal when i started with this mod was that i wanted to make 1.12 diving (also swimming) a pleasent experience. And the annoying automatic sinking is one of parts i dislike the most about vanilla diving/swimming.

**Comment by pimalel233** [comment]
Understandable, I have not though about it that way. I though of making it that you would have to prepare to swim if you wanted to have any heavy armor on yourself, theoretically something giving more than X armor for example. An enhancement would nullify the disadvantage so it would not be always bad, just more of a depth to it. Anyway, great work on the mod still!
