### ISSUE TITLE
Balance Inquiry for energy values

### ISSUE THREAD

**Issue by DoomRater** [Meldexun/BetterDiving#61]
**Question**
The only mod I have in my modpack that can charge the power cells is Immersive Engineering.  However, they seem to charge what appears to be futuristic equipment quite fast. It was able to add 20000RF to a dead power cell, filling it in roughly ten seconds.  This seems awfully fast for a mod nowhere near in the same scope of power as Subnautica...
Could I see some options to increase the base value of power cells, seeing as I can tweak their power consumption to match?

**Versions**
Better Diving: 1.4.14
Immersive Engineering: 0.12-92

**Comment by Meldexun** [comment]
One problem is that i have no idea how much RF is a big or a small amount. Also currently there is no way to charge a power cell/battery without other mods. That is all kind of unbalanced/just not nice. So if you know some tech mods you could also tell me what a reasonable amount for power cell could be. I also thought about increasing the value but as i said i don't really know other tech mods.

A config option for that might cause some problems because when client and server have different configs. But i probably should think about something to "fix" this.

**Comment by DoomRater** [comment]
In Subnautica, since materials regenerated over time it was a viable strategy to just make new power cells when the old ones died if you never found the technology to recharge them.  Here, I'm guessing materials in the ocean don't respawn.

Let's look at various mod power transfer.  Immersive Engineering can transfer 256, 1024, or 4096 IF energy through single connectors and its power lines can carry even more along a single line using multiple connectors.  But at these rates, the Charging Station fills it up within a few seconds.  I recall Subnautica's power cells taking quite a while to restore their full power, usually at least a minute or two.

But that's just Immersive Engineering.  Thermal Expansion can transfer several tiers of power, from 80 all the way up to an unlimited amount between points.  And its Energetic Infuser will attempt to dump its entire cache of energy into an object if the object can handle it.

Ender IO is even more aggressive with energy dumping as it scales with how big the capacitor multiblock is and the tier of capacitor block used.  And its biggest wires go up into the tens of thousands last I played with it.

But one thing on the description of the Energetic Infuser caught my eye, and it might make balancing the power cell a bit easier.  If the rate that the item can accept at once is low, the Infuser will only be able to add that much energy per tick.  Maybe enforcing something like that would be a good solution, which would prevent them from charging so quickly in various tech.  I think most charging solutions from other mods respect this.

As far as different configs go, this is something I hear other modders talk about being able to sync on connection, but in my case I can assure both my server and client will be using the same config values.

**Comment by Meldexun** [comment]
I'm not sure if in Subnautica resources regenerate naturally (outcrops and large deposites).

But that doesn't really matter i might increase the amount a battery/power cell can hold to 1 million/2 million. Also i know that i can change the maxReceive/maxExtract values. But currently i'm not sure wether i want to set these to values similar to be to Subnautica or similar to other tech mods.

Yes, config syncing is possible and i also do that already (for some reason minecraft handles movement on the client and then sends the information to the server...).
Currently i'm not sure how i want it to be in the future. But for now i might increase the capacity of batteries/power cells and maybe also decrease the transfer rate.

**Comment by DoomRater** [comment]
Trying out 1.5.0.  Yeah I like the power balance a lot more, because it feels like IE should be inefficient at charging these sorts of things.

**Comment by Meldexun** [comment]
I guess this was fixed in the past and thus can be closed now.

**Comment by DoomRater** [comment]
I haven't had any chance to test this out on versions beyond 1.12.2 as I'm version locked at the moment by my favorite mods.  But 1.5.8 didn't have any significant changes from 1.5.0 on charging and I'm satisfied with how things looked at that point.

**Comment by Meldexun** [comment]
1.16 has a config option to adjust the power cell to your needs.
