### ISSUE TITLE
Hardcore Darkness Incompability. 

### ISSUE THREAD

**Issue by Inf0214** [Meldexun/BetterDiving#62]
**Describe the bug**
With both mods installed, you cant see underwater. The diving gear makes little to no difference. 

**To Reproduce**
Install both mods, go underwater. 

**Versions**
Better Diving: 1.4.14
Forge: 14.23.5.2847
Minecraft: 1.12.2

**Other**
Night vision potion makes the darkness disappear. So I think it would be possible to use that effect once the player is underwater when HC Darkness is installed. 

I would really appreciate this fix and I am sure others would too, since both your and HC Darkness are very popular. 
![2020-04-08_14 11 32](https://user-images.githubusercontent.com/1087138/78782971-30962d80-79a3-11ea-8272-2fb69574dbda.png)
![2020-04-08_14 11 23](https://user-images.githubusercontent.com/1087138/78782987-34c24b00-79a3-11ea-8c0c-518d50a7f02c.png)
![2020-04-08_14 12 24](https://user-images.githubusercontent.com/1087138/78782979-31c75a80-79a3-11ea-94d2-fa51d4a0ed0a.png)
![2020-04-08_14 12 29](https://user-images.githubusercontent.com/1087138/78782981-33911e00-79a3-11ea-9895-3aa746141fd8.png)

**Comment by Meldexun** [comment]
I don't see a problem here. HardoreDarkness does exactly what it should/wants to. So why should I change something in my mod? Especially just adding night vision seems like dumb solution.
