### ISSUE TITLE
Fun with Seaglide!

### ISSUE THREAD

**Issue by DoomRater** [Meldexun/BetterDiving#64]
**Describe the bug**
Here are all the things I've noticed with the Seaglide:
-name and tooltip aren't working yet
-putting it in the offhand causes it to do nothing but it still renders in the center
-you can use offhand items like the bow while using the seaglide (not sure how you want to handle that?  Maybe make the seaglide do nothing if there is something in the other hand?)
-seaglide is faster than seamoth? I thought they were meant to be about equal.

**Versions**
Better Diving: 1.5.0
Minecraft: 1.12.2

**Comment by Meldexun** [comment]
Seaglide isn't officially implemented. Though it should already be exactly the same speed as the seamoth.
