### ISSUE TITLE
ArtemisLib Compatibility?

### ISSUE THREAD

**Issue by DoomRater** [Meldexun/BetterDiving#65]
**Describe the bug**
ArtemisLib allows the player to be _differently sized_.  Using Gulliver Reborn, or Resizing Potion, players can become larger or smaller than the usual 1.8 blocks high.  But when swimming with sprint, players will always end up the same size.

There's a little bit of freakout when popping in between the two, but nothing like what happens with SmartMoving.

**Versions**
Better Diving: 1.5.0
ArtemisLib: 1.0.6
Gulliver Reborn: 1.8
Forge: 14.23.5.2852
Minecraft: 1.12.2

**Other**
Currently only tested in singleplayer.

**Comment by Meldexun** [comment]
Should be fixed with v1.5.1.
