### ISSUE TITLE
Armourer's Workshop compatiblity with alternative player render?

### ISSUE THREAD

**Issue by DoomRater** [Meldexun/BetterDiving#66]
**Enhancement**
The replacement player model when sprint swimming currently has no idea what Armourer's Workshop is.  I've been told adding support for AW cosmetics isn't all that hard, but I suppose if I understood it I'd just file a pull request after doing so myself.

**Versions**
Better Diving: 1.5.0
Armourer's Workshop: 0.50.1.589
Forge: 14.23.5.2852
Minecraft: 1.12.2

**Comment by Meldexun** [comment]
So I removed the rendering of a custom player model in v1.5.1. Now it should work fine with Armourer's Workshop (maybe you can give me feedback).

**Comment by DoomRater** [comment]
Everything looks swimmingly now. I've repeated the tests with both Armourer's Workshop and attempting to swim with a giant player and everything looks amazing!

Additionally, I double-checked with Extra Bit Manipulation which also now works well too.  I'd call this one complete!
