### ISSUE TITLE
[Enhancement] Creepvine cluster Serene Seasons compatability?

### ISSUE THREAD

**Issue by pimalel233** [Meldexun/BetterDiving#69]
**Enhancement**
A bit more compatability with serene seasons on 1.12.2. It seems to be impossible to add better_diving:creepvine_seed_cluster to serene seasons compatability list of plants. It's the only plant that is not getting added, for example better_diving:creepvine works just fine.

**Versions**
Better Diving: 1.4.14 (have not checked newest version yet but in the changelog I have not notice anything that would fix it, just want to put it out there if it is something that can be fixed)
Forge: 2487
Minecraft: 1.12

Not working creepvine: http://prntscr.com/sacwk8 in serene config put as: better_diving:creepvine_seed_cluster
Working creepvine: http://prntscr.com/sacwo9 in serene config put as: better_diving:creepvine

**Comment by Meldexun** [comment]
Since the creepvine isn't a crop it (probably) doesn't change anything if you add this to the serene seasons config. So i don't really understand what you want.

**Comment by pimalel233** [comment]
Well, maybe I misunderstood it. Serene seasons cofig says to add a crop seed or the crop block itself, I though since I could plant this 'item' underwater it was a crop.
