### ISSUE TITLE
Unnamed item (name)

### ISSUE THREAD

**Issue by kellixon** [Meldexun/BetterDiving#7]
MC 1.12.2. BetterDiving 1.0.6.
The screenshot shows everything.
![2019-01-10_20 24 45](https://user-images.githubusercontent.com/22012731/50985821-4bff5800-1516-11e9-94fa-0224ddf40d3c.png)

**Comment by Meldexun** [comment]
Already noticed this. Will be fixed in new version. If you can't wait edit the lang file and insert a blank line at the top
