### ISSUE TITLE
Fish No Longer Spawn

### ISSUE THREAD

**Issue by nephatrine** [Meldexun/BetterDiving#71]
**Describe the bug**
None of the fish seem to be spawning. I had been using 1.4.14 and had no issues with it. I updated to 1.5.1, and now the fish no longer spawn naturally. I deleted the old config when I updated as advised on the curseforge page, and the default config it generated looks fine, just no fish spawn. The plants spawn just fine though.

I even tried cranking up the weights, spawn limits, etc. in the config but nothing got them spawning again.

**Versions**
Better Diving: 1.5.1
Forge: 14.23.5.2847
Minecraft: 1.12.2

**Other**
Singleplayer/Multiplayer: Both

**Comment by Meldexun** [comment]
Fixed in v1.5.2
