### ISSUE TITLE
Generation bug with other mods

### ISSUE THREAD

**Issue by Zack7292** [Meldexun/BetterDiving#72]
**Describe the bug**
when i put other mods that add underwater plants (in this case, Coral Reef and Underwater World)
the plant automatically broke themselves and create lots of item that can generate lots of lag or ram useless uses.

**To Reproduce**
1. add underwater world and Coral reef with,of course, this mod
2. generate a world
3. see those useless item inside of the ocean (to help you see them you could use Chunk animator and World tooltip)

**Versions**
Better Diving: 1.5.2
Forge: 2847
Minecraft: 1.12.2

**Other**
Singleplayer/Multiplayer: should be in both
Other mods (that are necessary to produce the bug):
https://www.curseforge.com/minecraft/mc-mods/underwater-world   https://www.curseforge.com/minecraft/mc-mods/coralreef

Other mods (that are also installed):  
https://www.curseforge.com/minecraft/mc-mods/chunk-animator
https://www.curseforge.com/minecraft/mc-mods/world-tooltips

**Comment by Meldexun** [comment]
I updated which material is required for the plants to be placeable on. That should solve the issue.
But this is generally the fault of the other mods.

**Comment by iMagic16** [comment]
I'm having this issue, Using Engineers Life on TTV/Curse.  the fish spawn like mad! https://i.imgur.com/WTvHaxh.png
