### ISSUE TITLE
weird "flying fish"

### ISSUE THREAD

**Issue by Zack7292** [Meldexun/BetterDiving#73]
**Describe the bug**
the fish can get so high in the water that it look like they are either flying on the water or sliding on to it
![Screenshot_378](https://user-images.githubusercontent.com/45187146/81623090-a0dc0880-93c0-11ea-8ec5-30e355d6fcb4.png)

**To Reproduce**
1.look at the fishes when they get on "top" of the water by themself

**Versions**
Better Diving: 1.5.2
Forge:2847
Minecraft: 1.12.2

**Other**
Crash report (if one exists): none
Latest log: none
Singleplayer/Multiplayer: both
Other mods (that are necessary to produce the bug): none
Other mods (that are also installed): this modpack https://www.curseforge.com/minecraft/modpacks/infinitely-exploring

**Comment by Meldexun** [comment]
Fixed in 1.5.3
