### ISSUE TITLE
Oxygen Can't breathe with vanilla oxygen mechanics in Seamoth

### ISSUE THREAD

**Issue by SebaSphere** [Meldexun/BetterDiving#76]
https://youtu.be/isKa4BuwvTA

**Describe the bug**
Can't breathe underwater in seamoth

**To Reproduce**
1. Change config to not use built in oxygen system
2. Oxygen bar still appears in seamoth
3. I couldn't figure out how to fill oxygen tanks but maybe it's the same thing???

**Versions**
Better Diving: 1.5.3
Forge: 2854
Minecraft: 1.12.2

**Other**
Crash report (if one exists):
Latest log:
Singleplayer/Multiplayer: Testing on singleplayer
Other mods (that are necessary to produce the bug):
Other mods (that are also installed):

**Comment by Meldexun** [comment]
Well you disabled a part of the mod. So i don't know what you expected. (Also in the video i don't see the oxygen bar)

**Comment by SebaSphere** [comment]
> Well you disabled a part of the mod. So i don't know what you expected. (Also in the video i don't see the oxygen bar)

I prefered the vanilla method of oxygen in my pack and noticed that happened with the sub.
