### ISSUE TITLE
Crash When Loading a New World

### ISSUE THREAD

**Issue by ScienceDrummer** [Meldexun/BetterDiving#80]
**Describe the bug**
Game crashes when loading a new world after exploring for a bit.

**To Reproduce**
1. Load up a new world
2. Crash will happen eventually

**Versions**
Better Diving: 1.5.5
Forge: 14.23.5.2854 
Minecraft: 1.12.2

**Other**
Crash report (if one exists): https://hastebin.com/uqolasisad.rb
https://hastebin.com/nibuwuhave.coffeescript (This one might not be related, but I got this crash before the one blaming Better Diving)
Latest log: [latest.log](https://github.com/Meldexun/BetterDiving/files/4968815/latest.log)
Singleplayer/Multiplayer: Singleplayer
Other mods (that are necessary to produce the bug): Not sure
Other mods (that are also installed): Check Crash Report

**Comment by Meldexun** [comment]
Fixed in v1.5.6
