### ISSUE TITLE
Rebreather/Oxygen Working with Vanilla Air Enabled

### ISSUE THREAD

**Issue by mxnmnm** [Meldexun/BetterDiving#82]
**Enhancement**
Things like the diving mask/rebreather/oxygen tanks should work even when the custom oxygen options are disabled. So it would maybe just add some extra bubbles if possible and the rebreather would have the bubbles go down more slowly.

**Comment by mxnmnm** [comment]
If you don't want to make the diving gear work with vanilla stats would it be possible for an option to disable the gear based on what was disabled in the configs so there aren't any useless items (aka disabling custom oxygen disabled the tanks).

**Comment by Meldexun** [comment]
> **Enhancement**
> Things like the diving mask/rebreather/oxygen tanks should work even when the custom oxygen options are disabled. So it would maybe just add some extra bubbles if possible and the rebreather would have the bubbles go down more slowly.

No, it doesn't really work nice and because of that I changed it.

> If you don't want to make the diving gear work with vanilla stats would it be possible for an option to disable the gear based on what was disabled in the configs so there aren't any useless items (aka disabling custom oxygen disabled the tanks).

Registering items based on config isn't a good modding standard. Also there are mods which let you remove recipes. That should be enough.
