### ISSUE TITLE
Creepvine instant growth

### ISSUE THREAD

**Issue by Jaeric217** [Meldexun/BetterDiving#85]
When on a server with better diving 1.5.7 the seed clusters will instantly grow along the entire length of the creepvine. When harvested the seed cluster will instantly replace itself. I've had this issue go away sometimes but it always comes back.

Here is a clip of the problem: [https://gyazo.com/592bad00d6527492ddf373e63e09320e](url)

**To Reproduce**
1. Install Better Diving 1.5.7 on a server and find creepvine growing in the ocean. You'll know the issue has occurred if the creepvine is completely covered in seed clusters.

**Versions**
Better Diving: 1.5.7
Forge: 1.12.2-14.23.5.2854
Minecraft: 1.12.2

**Other**
Crash report (if one exists): none
Latest log: 
[latest.log](https://github.com/Meldexun/BetterDiving/files/5397543/latest.log)

Singleplayer/Multiplayer: Multiplayer
Other mods (that are necessary to produce the bug): none
Other mods (that are also installed): none

**Comment by Meldexun** [comment]
Fixed in v1.5.8
