### ISSUE TITLE
What do the seamoth upgrade slots do? And what items fit on it?

### ISSUE THREAD

**Issue by luiginho3** [Meldexun/BetterDiving#86]
**Question**
Description of the question or problem you are encountering.

**Versions**
Better Diving:
Forge:
Minecraft:

**Other**
Crash report (if one exists):
Latest log:
Singleplayer/Multiplayer:
Other mods (that are necessary to produce the bug):
Other mods (that are also installed):

**Comment by Meldexun** [comment]
The upgrades are not implemented and so the slots are not usable.
