### ISSUE TITLE
Visual Issue With Swimming Alongside Ido (F5)

### ISSUE THREAD

**Issue by Stormalisk** [Meldexun/BetterDiving#89]
You are unable to swim in any other direction than upwards while in the third person while ido is also present.

During any moment you attempt to sprint underwater and are in the third person, the camera is forced to look upwards and you cannot change direction of your swim at all save removing yourself from the third person.

Better Diving: 1.5.8
Forge:  14.23.5.2847
Minecraft: 1.12.2
Ido: 1.1.0 (Have not been able to test 2.0.0-B for reasons I haven't figured out yet)

Tested on a modpack first by itself, no issues. Ido was added and the problem returned.

**Comment by Stormalisk** [comment]
Okay I managed to get 2.0.0-B working like right after I posted this, the previous problem does not seem to persist but they player now swims always facing down. This could be helpful on their end if it is their mods issue or not.

**Comment by Meldexun** [comment]
There is a config option to disable the player animations from better diving which should fix this.
