### ISSUE TITLE
Suit isn't rendered correctly on the player

### ISSUE THREAD

**Issue by CREEATION** [Meldexun/BetterDiving#9]
**With skin overlays enabled**:
![2019-03-17_21 41 07](https://user-images.githubusercontent.com/3277769/54500231-edda6100-491a-11e9-9921-5a38c28e4f08.png)
![2019-03-17_21 41 12](https://user-images.githubusercontent.com/3277769/54500232-edda6100-491a-11e9-9529-8268a9b2c79d.png)

**With skin overlays disabled**:
![2019-03-17_21 40 07](https://user-images.githubusercontent.com/3277769/54500215-c8e5ee00-491a-11e9-81c6-6082ad557fc2.png)
![2019-03-17_21 40 22](https://user-images.githubusercontent.com/3277769/54500216-cd120b80-491a-11e9-818c-e7e0672e2cf8.png)

**Comment by Meldexun** [comment]
Will take a look at it. Thank you.

**Comment by Meldexun** [comment]
In v1.2.0 all models should render correctly. (the file is uploaded to the curse network but it takes unusual long until they approve the file)

**Comment by CREEATION** [comment]
Hello again!
This is close to being perfect - just a few tweaks needed:

![2019-03-25_08 52 58](https://user-images.githubusercontent.com/3277769/54903194-9d936e00-4edb-11e9-91ed-380c01afb8f5.png)
![2019-03-25_08 53 09](https://user-images.githubusercontent.com/3277769/54903196-9d936e00-4edb-11e9-9660-20d877d4ce8f.png)

I think this has something to do with the arms moving ("breathing"), like when you stand still.

**Comment by Meldexun** [comment]
I can't seem to recreate your issue.
What version of my mod did you use? Maybe it's another mod you are playing with?

**Comment by CREEATION** [comment]
I was about to say that I don't play with mods which alter the player model in any way, and I thought I was right. After testing though, I've identified [Quark](https://quark.vazkii.net/) causing this error, but I don't really know why they alter the player model.

[I've opened an issue on their end](https://github.com/Vazkii/Quark/issues/1183), because Better Diving works just fine without Quark.
