### ISSUE TITLE
Oxygen GUI can't be scaled

### ISSUE THREAD

**Issue by MetalVortex** [Meldexun/BetterDiving#90]
**Enhancement**
I was configuring my GUI when I noticed theres no option to scale the GUI to fit how I'd like it organised. Its a small change but it would help a lot of modpack creators out

**Versions**
Better Diving: 1.5.8
Forge: 14.23.5.2854
Minecraft: 1.12.2

**Other**
Crash report (if one exists):
Latest log:
Singleplayer/Multiplayer:
Other mods (that are necessary to produce the bug):
Other mods (that are also installed):

**Comment by Meldexun** [comment]
1.12 isn't worked on anymore.
