### ISSUE TITLE
Incompatability, animation issues with Mobends

### ISSUE THREAD

**Issue by isaaachipkiss** [Meldexun/BetterDiving#92]
When using Mobends, sprinting underwater while facing down causes the player to flip sideways 

https://www.curseforge.com/minecraft/mc-mods/mo-bends

Steps to reproduce:
Install Mobends
enable player animations in Mobends gui
attempt to swim faster while looking down or slightly below standard camera height.

**Comment by Meldexun** [comment]
When 2 mods try to animate 1 model then either one mod "wins" or it will just be messed up. But there should be a config option to disable Better Diving animations.
