### ISSUE TITLE
Server not starting

### ISSUE THREAD

**Issue by pja1982** [Meldexun/BetterDiving#93]
**Describe the bug**
Server not starting

**To Reproduce**
Start Server

**Versions**
Better Diving: 1.16.5-1.0.1
Forge: 35.1.0
Minecraft: 1.16.5

**Other**
Crash report (if one exists):
Latest log:
https://pastebin.com/WGdueziK

Multiplayer:

**Comment by Meldexun** [comment]
Fixed in v1.16.5-1.1.0
