### ISSUE TITLE
Minecarts cannot be exited.

### ISSUE THREAD

**Issue by Endrez42** [Meldexun/BetterDiving#94]
Minecarts can no longer be exited by using the sneak key unless flying as in creative mode.

Steps:
1. Enter minecart (On or off rail)
2. Permanently stuck unless flying while also in minecart.

Versions:
Better Diving: 1.16.5 - 1.1.0
Forge: 1.16.5 - 36.0.13
Minecraft: 1.16.5

Singleplayer (Multiplayer likely)

No other mods installed.

NOTE: Versions 1.16.5-1.0.0 through latest version of Better Diving also have this bug. Likely due to Forge Beta

**Comment by VirtualGaming1** [comment]
not just minecart it also unable to dismount from horses or other mounts/rideable

(LATEST MOD VERSION: 1.1.0 MC: 1.6.4) NOTE: Forge for 1.6.5 is still in beta phase.

**Comment by Caboose298** [comment]
I did a test without the mod I can confirm this on my multiplayer server and in single player and i cant dismount from anything
and cannot use scaffold properly it seems like the keybind for sneaking is broken except for underwater ""but not the crouching action"".

**Comment by Meldexun** [comment]
Fixed in v1.16.5-1.1.1
