### ISSUE TITLE
Compatability with Aqua Acrobatics

### ISSUE THREAD

**Issue by mxnmnm** [Meldexun/BetterDiving#95]
**Describe the bug**
When the diving module is enabled, it ends up flattening the player's hitbox, but when it is disabled (which is probably what most people would do if they had aqua acrobatics installed with this mod) the swimming hitbox doesn't change. I'm guessing that whatever is being used to disable the module ends up accidentally disabling whatever aqua acrobatics does.

**To Reproduce**
Install both mods
Look at hitboxes while swimming

**Versions**
Better Diving: 1.5.8
Forge: 14.23.5.2854
Minecraft: 1.12.2
Singleplayer/Multiplayer: Singleplayer and probably Multiplayer
Other mods (that are necessary to produce the bug): Aqua Acrobatics

**Comment by Meldexun** [comment]
Set better diving -> client settings -> customPlayerModel to false
