### ISSUE TITLE
Client crash on key input

### ISSUE THREAD

**Issue by TylerHaynie** [Meldexun/BetterDiving#96]
**Describe the bug**
If the mod is enabled and you try to add a new multiplayer IP, the client will crash.

**To Reproduce**
1. Launch forge client with mod enabled
2. Click multiplayer and try to add a new IP or Server Name

**Versions**
Better Diving: 1.16.5-1.2.0
Forge: 36.0.42
Minecraft: 1.16.5

> java.lang.NullPointerException: Unexpected error
> 	at meldexun.better_diving.client.event.ClientEventHandler.onKeyInputEvent(ClientEventHandler.java:89) ~[?:?] {re:classloading}
> 	at net.minecraftforge.eventbus.ASMEventHandler_289_ClientEventHandler_onKeyInputEvent_KeyInputEvent.invoke(.dynamic) ~[?:?] {}
> 	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
> 	at net.minecraftforge.eventbus.EventBus$$Lambda$2551/1605951394.invoke(Unknown Source) ~[?:?] {}
> 	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
> 	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
> 	at net.minecraftforge.client.ForgeHooksClient.fireKeyInput(ForgeHooksClient.java:729) ~[?:?] {re:classloading}
> 	at net.minecraft.client.KeyboardListener.func_197961_a(KeyboardListener.java:356) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
> 	at net.minecraft.client.KeyboardListener.lambda$null$7(KeyboardListener.java:391) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
> 	at net.minecraft.client.KeyboardListener$$Lambda$12921/1913376680.run(Unknown Source) ~[?:?] {}
> 	at net.minecraft.util.concurrent.ThreadTaskExecutor.execute(SourceFile:94) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
> 	at net.minecraft.client.KeyboardListener.lambda$setupCallbacks$8(KeyboardListener.java:390) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
> 	at net.minecraft.client.KeyboardListener$$Lambda$2846/1336437944.invoke(Unknown Source) ~[?:?] {}
> 	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:37) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
> 	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10] {}
> 	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
> 	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(SourceFile:127) ~[?:?] {re:classloading}
> 	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:999) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
> 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
> 	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
> 	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
> 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.0.42.jar:36.0] {}
> 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$480/18459190.call(Unknown Source) [forge-1.16.5-36.0.42.jar:36.0] {}
> 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
> 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
> 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
> 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
> 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}

**Comment by Meldexun** [comment]
Fixed in v1.16.5-1.2.1
