### ISSUE TITLE
[1.12.2 (Doubt this is even supported.)] Fog causing weird rendering.

### ISSUE THREAD

**Issue by MagmaBro123** [Meldexun/BetterDiving#98]
**Describe the bug**
Title.

**To Reproduce**
Go to the Better Diving config, and enable fog coloration.

**Versions**
Better Diving: BetterDiving 1.5.8.
Forge: 2854.
Minecraft: 1.12.2.

**Other**
Crash report (if one exists): N/A.
Latest log: N/A.
Singleplayer/Multiplayer: Single.
Other mods (that are necessary to produce the bug): Tested in a modpack. Same issue.
Other mods (that are also installed): Tested on its own. Same issue.

![2021-02-22_11 06 18](https://user-images.githubusercontent.com/51277766/108752351-32ec7200-74f8-11eb-84d0-fdb30ab2d5ac.png)

**Comment by Meldexun** [comment]
That's why it's disabled by default. You can report it to mojang.
